# Generated by Django 3.2 on 2021-05-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.catalog', verbose_name='Konu'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='konu Resmi'),
        ),
    ]
