# Generated by Django 3.2 on 2021-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210514_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makalenizi anlatacak detaylı resim ekleyebilirsiniz. (Opsiyonel)'),
        ),
    ]
