# Generated by Django 3.2 on 2021-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='makalenizi açıklayın', verbose_name='İçerik'),
        ),
    ]
