# Generated by Django 3.2 on 2021-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='detail_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(help_text='makalenizi açıklayın', max_length=2000, verbose_name='İçerik'),
        ),
    ]
