# Generated by Django 3.2 on 2021-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_profile_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
