# Generated by Django 3.2 on 2021-05-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_article_article_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_profile_image',
        ),
    ]
