# Generated by Django 3.2 on 2021-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Resim Yükleyin'),
        ),
    ]
